# sqlplex.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ADD', 'AFTER', 'ALL', 'ALTER', 'AND', 'ANY', 'AS', 'ASC', 'AUTO_INCREMENT', 'AVG', 'BEFORE', 'BEGIN', 'BETWEEN', 'BIGINT', 'BITWISE_AND', 'BITWISE_OR', 'BITWISE_XOR', 'BIT_AND', 'BIT_OR', 'BIT_XOR', 'BLOB', 'BY', 'CASCADE', 'CASE', 'CAST', 'CHAIN', 'CHANGE', 'CHAR', 'CHARACTER', 'CHARSET', 'CLOSE', 'COLLATE', 'COLUMN', 'COMMENTS', 'COMMIT', 'CONSISTENT', 'CONSTRAINT', 'CONVERT', 'COUNT', 'CREATE', 'CROSS', 'CUBE', 'DATE', 'DATETIME', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DELAYED', 'DELETE', 'DELIM', 'DELIMITER', 'DESC', 'DISTINCT', 'DIV', 'DO', 'DROP', 'DUAL', 'DUPLICATE', 'EACH', 'ELSE', 'ELSEIF', 'END', 'ENGINE', 'EQ', 'ESCAPE', 'EXISTS', 'FALSE', 'FETCH', 'FIRST', 'FLOAT', 'FLOAT_LIT', 'FOR', 'FORCE', 'FROM', 'GE', 'GLOBAL', 'GROUP', 'GT', 'HAVING', 'HIGH_PRIORITY', 'IDENT', 'IF', 'IGNORE', 'IN', 'INDEX', 'INNER', 'INSERT', 'INT', 'INTEGER', 'INTO', 'IS', 'ITERATE', 'JOIN', 'KEY', 'LE', 'LEAVE', 'LEFT', 'LIKE', 'LIMIT', 'LOCK', 'LOGICAL_NOT', 'LONGBLOB', 'LONGTEXT', 'LOOP', 'LOW_PRIORITY', 'LT', 'MAX', 'MEDIUMBLOB', 'MEDIUMINT', 'MEDIUMTEXT', 'MIN', 'MINUS', 'MOD', 'MODE', 'MODIFY', 'NATURAL', 'NE', 'NEXT', 'NO', 'NOT', 'NULL', 'NULL_SAFE', 'NUMBER', 'NUMERIC', 'OFFSET', 'ON', 'OPEN', 'OPTIMIZE', 'OR', 'ORDER', 'OUTER', 'PLUS', 'PRIMARY', 'QUICK', 'REGEXP', 'RELEASE', 'RENAME', 'REPEAT', 'REPLACE', 'RESTRICT', 'RETURN', 'RIGHT', 'ROLLBACK', 'ROLLUP', 'ROW', 'SELECT', 'SESSION', 'SET', 'SET_VAR', 'SHARE', 'SHL', 'SHR', 'SIGNED', 'SMALLINT', 'SNAPSHOT', 'SOME', 'SOUNDS', 'START', 'STRING', 'SUM', 'TABLE', 'TEMPORARY', 'TEXT', 'THEN', 'TIME', 'TIMES', 'TIMESTAMP', 'TINYBLOB', 'TINYINT', 'TINYTEXT', 'TO', 'TRANSACTION', 'TRIGGER', 'TRUE', 'UNION', 'UNIQUE', 'UNKNOWN', 'UNSIGNED', 'UNTIL', 'UPDATE', 'USE', 'USING', 'VALUE', 'VALUES', 'VARCHAR', 'VIEW', 'WHEN', 'WHERE', 'WHILE', 'WITH', 'WORK', 'XOR'))
_lexreflags   = 64
_lexliterals  = ',();*@'
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NEWLINE>\\r?\\n+)|(?P<t_COMMENTS>/\\*(.|[\\r\\n])*?\\*/|--[^\\n]*|\\#[^\\n]*)|(?P<t_FLOAT_LIT>(\\d+\\.\\d+([Ee](\\+|-)?\\d+)?|\\d+[Ee][+-]?\\d+))|(?P<t_NUMBER>-?\\d+)|(?P<t_STRING>"(\\\\"|""|[^"])*"|\\\'(\\\\\\\'|\\\'\\\'|[^\\\'])*\\\')|(?P<t_DELIMITER>(?i)DELIMITER[ \\t]+(?P<new_delim>[^ \\t\\n]+))|(?P<t_IDENT>[A-Za-z_][\\w_.]*|`(``|[^`])*`)|(?P<t_NE><>|!=)|(?P<t_OR>\\|\\|)|(?P<t_DELIM>[;])|(?P<t_NULL_SAFE><=>)|(?P<t_LE><=)|(?P<t_GE>>=)|(?P<t_AND>&&)|(?P<t_SET_VAR>:=)|(?P<t_BITWISE_OR>\\|)|(?P<t_TIMES>\\*)|(?P<t_PLUS>\\+)|(?P<t_SHR>>>)|(?P<t_SHL><<)|(?P<t_LOGICAL_NOT>!)|(?P<t_MINUS>-)|(?P<t_DIV>/)|(?P<t_BITWISE_AND>&)|(?P<t_GT>>)|(?P<t_BITWISE_XOR>^)|(?P<t_MOD>%)|(?P<t_LT><)|(?P<t_EQ>=)', [None, ('t_NEWLINE', 'NEWLINE'), ('t_COMMENTS', 'COMMENTS'), None, ('t_FLOAT_LIT', 'FLOAT_LIT'), None, None, None, ('t_NUMBER', 'NUMBER'), ('t_STRING', 'STRING'), None, None, ('t_DELIMITER', 'DELIMITER'), None, ('t_IDENT', 'IDENT'), None, (None, 'NE'), (None, 'OR'), (None, 'DELIM'), (None, 'NULL_SAFE'), (None, 'LE'), (None, 'GE'), (None, 'AND'), (None, 'SET_VAR'), (None, 'BITWISE_OR'), (None, 'TIMES'), (None, 'PLUS'), (None, 'SHR'), (None, 'SHL'), (None, 'LOGICAL_NOT'), (None, 'MINUS'), (None, 'DIV'), (None, 'BITWISE_AND'), (None, 'GT'), (None, 'BITWISE_XOR'), (None, 'MOD'), (None, 'LT'), (None, 'EQ')])]}
_lexstateignore = {'INITIAL': ' \t\x0c'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
